### ISSUE TITLE
Impossible to compact on BUILD_ITERATOR

### ISSUE THREAD

**Issue by Anahkiasen** [kherge-archive/lib-phar#2]
I add files to my Phar via an iterator (from a Symfony Finder instance), however when I try to run the compilation I get this:

```
PHP Fatal error:  Uncaught exception 'Phine\Compact\Exception\CompactException' with message 'The subject "Phine\Phar\Subject\Builder\BuildIterator" is not supported.' in /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/exception/src/lib/Phine/Exception/Exception.php:43
Stack trace:
#0 /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar-compact/src/lib/Phine/Phar/Compact/CompactObserver.php(86): Phine\Exception\Exception::createUsingFormat('The subject "%s...', 'Phine\\Phar\\Subj...')
#1 /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/observer/src/lib/Phine/Observer/Subject.php(177): Phine\Phar\Compact\CompactObserver->receiveUpdate(Object(Phine\Phar\Subject\Builder\BuildIterator))
#2 /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar/src/lib/Phine/Phar/Subject/AbstractSubject.php(106): Phine\Observer\Subject->notifyObservers()
#3 /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar/src/lib/Phine/Phar/Builder.php(468): Phine\Phar\Subject\AbstractSubject->notifyObservers()
#4  in /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/exception/src/lib/Phine/Exception/Exception.php on line 43

Fatal error: Uncaught exception 'Phine\Compact\Exception\CompactException' with message 'The subject "Phine\Phar\Subject\Builder\BuildIterator" is not supported.' in /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/exception/src/lib/Phine/Exception/Exception.php on line 43

Phine\Compact\Exception\CompactException: The subject "Phine\Phar\Subject\Builder\BuildIterator" is not supported. in /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/exception/src/lib/Phine/Exception/Exception.php on line 43

Call Stack:
    0.0002     235024   1. {main}() /Users/anahkiasen/Sites/rocketeers/rocketeer/bin/compile:0
    0.0051     976616   2. Rocketeer\Console\Compiler->compile() /Users/anahkiasen/Sites/rocketeers/rocketeer/bin/compile:7
    0.0075    1302072   3. Rocketeer\Console\Compiler->addFolder() /Users/anahkiasen/Sites/rocketeers/rocketeer/src/Rocketeer/Console/Compiler.php:100
    0.0217    1892192   4. Phine\Phar\Builder->buildFromIterator() /Users/anahkiasen/Sites/rocketeers/rocketeer/src/Rocketeer/Console/Compiler.php:176
    0.0217    1892736   5. Phine\Phar\Builder->invokeEvent() /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar/src/lib/Phine/Phar/Builder.php:317
    0.0220    1913504   6. Phine\Phar\Subject\AbstractSubject->notifyObservers() /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar/src/lib/Phine/Phar/Builder.php:468
    0.0220    1913736   7. Phine\Observer\Subject->notifyObservers() /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/phine/phar/src/lib/Phine/Phar/Subject/AbstractSubject.php:106
```

Is there no way to compact on iterator adds ? That used to work with herrera-io/php-box

**Comment by Anahkiasen** [comment]
On an unrelated note I'm switching to this because I saw the deprecation notice on php-box but this project doesn't really seem maintained either, is this the right package to switch to ?
